version = 1

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "ember"
  ]
  environment = [
    "nodejs",
    "browser",
    "mongo",
    "jquery"
  ]

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/unnita1235/TenantVerse"
  dependencies_vendored = true

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "dart-analyze"
type = "community"

[[analyzers]]
name = "slither"
type = "community"

[[analyzers]]
name = "solhint"
type = "community"

[[analyzers]]
name = "kube-linter"
type = "community"

[[analyzers]]
name = "cfn-lint"
type = "community"

[[code_formatters]]
name = "isort"

[[code_formatters]]
name = "yapf"

[[code_formatters]]
name = "autopep8"

[[code_formatters]]
name = "black"

[[code_formatters]]
name = "ruff"

[[code_formatters]]
name = "google-java-format"

[[code_formatters]]
name = "dotnet-format"

[[code_formatters]]
name = "clang-format"

[[code_formatters]]
name = "gofmt"

[[code_formatters]]
name = "gofumpt"

[[code_formatters]]
name = "ktlint"

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "standardjs"

[[code_formatters]]
name = "scalafmt"

[[code_formatters]]
name = "rustfmt"

[[code_formatters]]
name = "standardrb"

[[code_formatters]]
name = "rubocop"